# Generated by Django 3.2.6 on 2021-09-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.BooleanField(default=False)),
                ('comp_id', models.IntegerField()),
                ('F_usr', models.IntegerField()),
                ('T_usr', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('data', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='E:\\Study\\SEM 7\\Capstone Project-III\\FSS\\media')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('p_pic', models.ImageField(blank=True, upload_to='static')),
                ('p_desc', models.CharField(blank=True, max_length=1000)),
                ('own_comp', models.BooleanField(blank=True, default=False)),
                ('comp_name', models.CharField(blank=True, max_length=100)),
                ('Fr_obj', models.CharField(blank=True, max_length=100000)),
            ],
        ),
    ]
