# Generated by Django 3.2.6 on 2021-09-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSSApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
