# Generated by Django 4.1.2 on 2023-11-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_favoriteitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitem',
            name='algorithm',
            field=models.CharField(default='Your Default Algorithm', max_length=255),
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='custom_key',
            field=models.BooleanField(default=False),
        ),
    ]
