# Generated by Django 4.1.2 on 2023-11-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_favoriteitem_algorithm_favoriteitem_custom_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteitem',
            name='algorithm',
            field=models.CharField(default='AES', max_length=100),
        ),
    ]
